# Generated by Django 4.1.2 on 2022-10-27 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cheque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sum",
                    models.PositiveIntegerField(
                        help_text="Введите сумму чека", verbose_name="Сумма чека"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название продукта",
                        max_length=100,
                        verbose_name="Название продукта",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        help_text="Введите цену продукта", verbose_name="Цена продукта"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название роли",
                        max_length=100,
                        verbose_name="Название роли",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cheque",
                    models.ForeignKey(
                        help_text=" Выберите чек",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donatellos_pizza_app.cheque",
                        verbose_name="Чек",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text=" Выберите продукт",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donatellos_pizza_app.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Введите имя с заглавной буквы",
                        max_length=100,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True,
                        help_text="Введите отчество",
                        max_length=100,
                        null=True,
                        verbose_name="Отчество",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Введите фамилию",
                        max_length=100,
                        verbose_name="Фамилия",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        help_text=" Выберите роль пользователя",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donatellos_pizza_app.role",
                        verbose_name="Роль пользователя",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Basket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cheque",
                    models.ForeignKey(
                        help_text=" Выберите чек",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donatellos_pizza_app.cheque",
                        verbose_name="Чек",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text=" Выберите пользователя",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donatellos_pizza_app.user",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
