# Generated by Django 4.1.3 on 2022-11-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donatellos_pizza_app", "0002_alter_product_category_productinbasket"),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="products",
            field=models.ManyToManyField(
                through="donatellos_pizza_app.ProductInBasket",
                to="donatellos_pizza_app.product",
            ),
        ),
    ]
