# Generated by Django 4.1.3 on 2022-12-04 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("donatellos_pizza_app", "0003_basket_products"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Введите адрес клиента",
                        max_length=100,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "order_time",
                    models.DateTimeField(
                        help_text="Введите время заказа", verbose_name="Время заказа"
                    ),
                ),
                (
                    "delivery_time",
                    models.DateTimeField(
                        help_text="Указать ожидаемое время доставки",
                        verbose_name="Время доставки",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        help_text="Введите статус заказа", verbose_name="Статус заказа"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="basket", name="cheque",),
        migrations.DeleteModel(name="Cheque",),
        migrations.AddField(
            model_name="basket",
            name="order",
            field=models.ForeignKey(
                blank=True,
                help_text=" Выберите чек",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="donatellos_pizza_app.order",
                verbose_name="Чек",
            ),
        ),
    ]
