# Generated by Django 4.1.3 on 2022-12-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "donatellos_pizza_app",
            "0004_order_remove_basket_cheque_delete_cheque_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="status",
            field=models.BooleanField(
                default=False,
                help_text="Введите статус заказа",
                verbose_name="Статус заказа",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.BooleanField(
                default=False,
                help_text="Введите статус заказа",
                verbose_name="Статус заказа",
            ),
        ),
    ]
