# Generated by Django 4.1.3 on 2022-12-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donatellos_pizza_app", "0005_basket_status_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="basket", name="order",),
        migrations.AddField(
            model_name="basket",
            name="address",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Введите адрес клиента",
                max_length=100,
                null=True,
                verbose_name="Адрес",
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="delivered_status",
            field=models.BooleanField(
                default=False,
                help_text="Введите статус доставки заказа",
                verbose_name="Статус доставки заказа",
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="delivery_time",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Указать ожидаемое время доставки",
                null=True,
                verbose_name="Время доставки",
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="order_time",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Введите время заказа",
                null=True,
                verbose_name="Время заказа",
            ),
        ),
        migrations.DeleteModel(name="Order",),
    ]
